services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: apib_gptci_api
    ports:
      - "30001:30001"
    volumes:
      - ./api:/api

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: apib_gptci_app
    ports:
      - "30002:3000"
    volumes:
      - ./app:/app
