services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: apib_gptci_api
    ports:
      - "30001:8000"
    volumes:
      - ./api:/api
      - /volume1/homes/dannyho/deployments_data:/deployment_datas

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: apib_gptci_app
    ports:
      - "30002:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
